#!/bin/sh

pre-commit

pre_commit_exit_code=$?

cd frontend || exit 1

npm run prettier

prettier_exit_code=$?

cd ..

if [ $pre_commit_exit_code -ne 0 ] || [ $prettier_exit_code -ne 0 ]; then
    exit 1
fi

exit 0
